require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'coffida_ui' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  target 'coffida_uiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'coffida_ui-tvOS' do
  # Pods for coffida_ui-tvOS

  target 'coffida_ui-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
